name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - labeled    # 可以选择其他触发条件，比如 PR 添加特定标签时触发
      - synchronize

  check_suite:
    types: [completed]  # 当测试完成时触发

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}  # 仅在源仓库的PR触发

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto-merge Pull Request
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: squash # 选择合并方式，可改为 'merge' 或 'rebase'
          commit-message: "Auto-merged after successful checks"
          required-labels: "ready-to-merge" # 设置一个标签如“ready-to-merge”来标记通过的PR
          required-approving-review-count: 1 # 设置需要的批准数量（可选）
          delete-branch: true # 合并后删除分支（可选）
